In [2]:
pip install numpy pandas scikit-learn seaborn jupyter

Defaulting to user installation because normal site-packages is not writeable
  Using cached isoduration-20.11.0-py3-none-any.whl.metadata (5.7 kB)
   ---------------------------------------- 0.0/238.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/238.1 kB ? eta -:--:--
   - -------------------------------------- 10.2/238.1 kB ? eta -:--:--
   ----- --------------------------------- 30.7/238.1 kB 330.3 kB/s eta 0:00:01
   --------------- ----------------------- 92.2/238.1 kB 655.4 kB/s eta 0:00:01
   ---------------------------------------- 238.1/238.1 kB 1.5 MB/s eta 0:00:00
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------  1.5/1.5 MB 49.2 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 24.7 MB/s eta 0:00:00
Using cached isoduration-20.11.0-py3-none-any.whl (11 kB)
  Attempting uninstall: jupyterlab-widgets
    Found existing installation: jupyterlab_widgets 3.0.13
    Uninstallin

In [3]:
import pandas as pd

In [4]:
import numpy as np

In [5]:
pd.__version__

'2.2.2'

In [8]:
df= pd.read_csv("laptops.csv")

In [9]:
df

Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           Model                CPU  RAM  Storage Storage type       GPU  \
0     ExpertBook      Intel Core i5    8      512          SSD       NaN   
1             Go      Intel Celeron    8      256          SSD       NaN   
2     ExpertBook      Intel Core i3    8      256          SSD       NaN   
3         Katana      Intel Core i7   16     1000          SSD  RTX 3050   
4            15S      Intel Core i5   16      512          SSD       NaN   
...          ...                ...  ...      ...          ...       ...   
2155       Blade      Intel Core i7   16     1000          SSD  RTX 3060   
2156       Blade      Intel Core i7   16     1000          SSD  RTX 3070   
2157       Blade      Intel Core i7   32     1000          SSD  RTX 3080   
2158        Book  Intel Evo Core i7   16     1000          SSD       NaN   
2159        Book  Intel Evo Core i7   16      256          SSD       NaN   

      Screen Touch  Final Price  
0       15.6    No      1009.00  
1       15.6    No       299.00  
2       15.6    No       789.00  
3       15.6    No      1199.00  
4       15.6    No       669.01  
...      ...   ...          ...  
2155    17.3    No      2699.99  
2156    17.3    No      2899.99  
2157    17.3    No      3399.99  
2158    13.4   Yes      1899.99  
2159    13.4   Yes      1699.99  

[2160 rows x 12 columns]

In [11]:
df['Brand'].nunique()

27

In [12]:
df.isnull()

Laptop  Status  Brand  Model    CPU    RAM  Storage  Storage type  \
0      False   False  False  False  False  False    False         False   
1      False   False  False  False  False  False    False         False   
2      False   False  False  False  False  False    False         False   
3      False   False  False  False  False  False    False         False   
4      False   False  False  False  False  False    False         False   
...      ...     ...    ...    ...    ...    ...      ...           ...   
2155   False   False  False  False  False  False    False         False   
2156   False   False  False  False  False  False    False         False   
2157   False   False  False  False  False  False    False         False   
2158   False   False  False  False  False  False    False         False   
2159   False   False  False  False  False  False    False         False   

        GPU  Screen  Touch  Final Price  
0      True   False  False        False  
1      True   False  False        False  
2      True   False  False        False  
3     False   False  False        False  
4      True   False  False        False  
...     ...     ...    ...          ...  
2155  False   False  False        False  
2156  False   False  False        False  
2157  False   False  False        False  
2158   True   False  False        False  
2159   True   False  False        False  

[2160 rows x 12 columns]

In [13]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [14]:
df['Final Price'].max()

7150.47

In [17]:
dell_notebooks = df[df['Brand']=='Dell']

In [18]:
dell_notebooks['Final Price'].max()

3936.0

In [19]:
df.describe()

RAM      Storage       Screen  Final Price
count  2160.000000  2160.000000  2156.000000  2160.000000
mean     15.413889   596.294444    15.168112  1312.638509
std       9.867815   361.220506     1.203329   911.475417
min       4.000000     0.000000    10.100000   201.050000
25%       8.000000   256.000000    14.000000   661.082500
50%      16.000000   512.000000    15.600000  1031.945000
75%      16.000000  1000.000000    15.600000  1708.970000
max     128.000000  4000.000000    18.000000  7150.470000

In [25]:
initial_median = df['Screen'].median()
initial_median

15.6

In [27]:
i_mode = df['Screen'].mode()[0]
i_mode

15.6

In [28]:
df['Screen'].fillna(i_mode, inplace = True)

C:\Users\jayas\AppData\Local\Temp\ipykernel_2212\91366200.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Screen'].fillna(i_mode, inplace = True)


In [30]:
new_median = df['Screen'].median()
new_median

15.6

In [35]:
Innjoo = df[df['Brand']=='Innjoo'][['RAM','Storage','Screen']]
Innjoo

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [36]:
X = Innjoo.to_numpy()
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [37]:
XT = X.T
XT

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [39]:
XTX = XT @ X
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [40]:
XTX_Inv = np.linalg.inv(XTX)
XTX_Inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [41]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [42]:
w1 = XTX_Inv @ XT
w1

array([[ 0.26298349, -0.12560233, -0.40646389,  0.14958687,  0.05244042,
         0.05244042],
       [-0.00110155,  0.00295059,  0.00125892, -0.00177691, -0.00076387,
        -0.00076387],
       [-0.08772226,  0.0269791 ,  0.17140891, -0.0302108 , -0.00153546,
        -0.00153546]])

In [43]:
w = w1 @ y
w

array([45.58076606,  0.42783519, 45.29127938])

In [44]:
result_sum = np.sum(w)
result_sum

91.29988062995496